name: CI
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
   runs-on: ubuntu-latest
   
   steps:
     - uses: actions/checkout@v2

     - name: Setup Node
       uses: actions/setup-node@v1

     - name: Get yarn cache directory path
       id: yarn-cache-dir-path
       run: echo "::set-output name=dir::$(yarn cache dir)"

     - uses: actions/cache@v1
       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
       with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

     - name: Install dependencies
       uses: borales/actions-yarn@v2.0.0
       with:
         cmd: install

     - name: Run linter
       run: npx elm-format --validate src/ docs/

     - name: Run analyse
       run: npx elm-analyse

  validate:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Validate docs code
         working-directory: ./docs
         run: npx elm make src/Main.elm --output /dev/null

  tests:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Setup Node
         uses: actions/setup-node@v1
       
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
         run: echo "::set-output name=dir::$(yarn cache dir)"

       - uses: actions/cache@v1
         id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
         with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

       - name: Install dependencies
         uses: borales/actions-yarn@v2.0.0
         with:
           cmd: install

       - name: Run tests
         run: yarn run test
