name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
   runs-on: ubuntu-latest
   if: github.event.pull_request.draft == false

   steps:
     - uses: actions/checkout@v2

     - name: Setup Node
       uses: actions/setup-node@v2.1.4
       with:
        node-version: '12'

     - name: Get yarn cache directory path
       id: yarn-cache-dir-path
       run: echo "::set-output name=dir::$(yarn cache dir)"

     - uses: actions/cache@v2.1.3
       id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
       with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

     - uses: PaackEng/elm-lint-action@main

  validate:
     runs-on: ubuntu-latest
     if: github.event.pull_request.draft == false

     steps:
       - uses: actions/checkout@v2

       - name: Validate showcase code
         working-directory: ./showcase
         run: npx elm make src/Main.elm --output /dev/null

       - name: Run docs
         run: npx elm make --docs=/tmp/docs.json

  tests:
     runs-on: ubuntu-latest
     if: github.event.pull_request.draft == false

     steps:
       - uses: actions/checkout@v2

       - name: Setup Node
         uses: actions/setup-node@v2.1.4
         with:
          node-version: '12'

       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
         run: echo "::set-output name=dir::$(yarn cache dir)"

       - uses: actions/cache@v2.1.3
         id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
         with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

       - name: Install dependencies
         run: yarn install

       - name: Run tests
         run: yarn run test

       - name: Build
         run: yarn run build

