name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - uses: PaackEng/elm-validate-action@v1.1.1
        with:
          elm-make-options:
          elm-review-extra-options: --ignore-dirs 'src/I18n'

      - uses: PaackEng/elm-validate-action@v1.1.1
        with:
          elm-working-directory: 'showcase'
          elm-review-extra-options: --ignore-dirs '../src'

  tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test
