name: Deploy

on: [deployment]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install and Build
        run: |
          yarn install
          yarn run build

      - name:  Deploy
        run: yarn run deploy
